# name: Pull Request Check

# on:
#   push:
#     branches:
#       - soni
#   pull_request:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print Message
#         run: echo "Hello, World!"

#       - name: Show GitHub event details
#         run: |
#           echo "Workflow is running successfully."
#           echo "Event: ${{ github.event_name }}"
#           echo "Source branch: ${{ github.head_ref || github.ref_name }}"
#           echo "Target branch: ${{ github.base_ref }}"

# on: Push
# Jobs:
#   run-test:
#     runs-on: ubuntu-latest
    
#     steps:
#       -run: echo "test is running"
#       -run: echo "test successful"
  
#   deploy_App:
#     needs: run_test
#     runs-on: ubuntu-latest
#     steps:
#       -run: echo "workflow successful"
# on: push
# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4
#       - name: List files
#         run: ls
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Check Node.js version
        run: node -v
        